@rootApi = http://localhost:8000
@userApi = {{rootApi}}/api/v1/user
@burrowApi = {{rootApi}}/api/v1/burrow

@reviewApi = {{rootApi}}/api/v1/review
###
GET {{rootApi}}

#=========== api for user
###
GET {{burrowApi}}


###
POST {{userApi}}
Content-Type: application/json

{
    "role":"student",
    "fName":"Sam",
    "lName":"Smith",
    "phone":"0978",
    "email":"sam@2mail",
    "password": "password",
    "address":"Street 234, Bangkok"

}
###
GET {{reviewApi}}